version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: gestion_proyectos
      MYSQL_USER: usuario_app
      MYSQL_PASSWORD: contraseña_segura
      MYSQL_ROOT_PASSWORD: root_seguro
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

